version: '3.1'

services:
  mongo:
    image: mongo:latest
    restart: always
    container_name: mongo-ppg
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017-27019:27017-27019"
    volumes:
    - /home/pmwaniki/data/ppg/mongo:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express-ppg
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example