version: '3.1'
#sudo docker run --rm --ulimit nofile=64000:64000 -e MONGO_INITDB_ROOT_USERNAME=root -e MONGO_INITDB_ROOT_PASSWORD=example -p 27017:27017 --name test-mongo mongo
services:
  mongo:
    image: mongo:latest
    restart: always
    container_name: mongo-ppg
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
    - /home/pmwaniki/data/ppg/mongo:/data/db
    ulimits:
      nofile:
        soft: 64000
        hard: 64000

  mongo-express:
    image: mongo-express
    container_name: mongo-express-ppg
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example